# Generated by Django 5.1.1 on 2024-09-09 15:58

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exemple", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("name", "supplier")},
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together={("name", "country")},
        ),
    ]
