# Generated by Django 5.1.1 on 2024-09-09 16:12

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exemple", "0002_brand_slug_country_slug_supplier_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Marque", "verbose_name_plural": "Marques"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Pays", "verbose_name_plural": "Pays"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="supplier",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nom de la marque"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="slug de la marque",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exemple.supplier",
                verbose_name="fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nom du pays"),
        ),
        migrations.AlterField(
            model_name="country",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="slug du pays",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exemple.country",
                verbose_name="pays",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nom du fournisseur"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                unique=True,
                verbose_name="slug du fournisseur",
            ),
        ),
    ]
